### ISSUE TITLE
is it necessary to masked repetitive regions from the same scaffolds? 

### ISSUE THREAD

**Issue by bitcometz** [adeylab/fragScaff#1]
Hello,

I think fragScaff will filter reads aligned to repetitive regions, defined by "Repeat bed file". And this file is generated by all vs all blast. So this bed file contained highly homologous regions from the same scaffolds( at least 100bp distance ).
So I am wondering is it necessary to masked highly homologous regions just identified on the same scaffolds, since reads from these homologous regions all represent the links of the same scaffold with other scaffolds, which I think will not cause assembly errors.

Thanks!

**Comment by acadey** [comment]
It is necessary because the main goal of the linked reads is to join ends of scaffolds - if there is a region of homology in the middle of a scaffold that could throw off the matching.
